"""种子题库：7-9 岁（小学 1-3 年级）的挑战内容，70 题。

题库是"个性化挑战"的廉价底座——预生成、可离线、答对走规则、零边际成本；
只有"答错的讲解引申"在真实产品里才花一次 LLM（本库用预置 explain/extend 模拟）。

每条题：kind / difficulty(1-3) / 判分方式。客观题给 answer + accept（关键词命中即对，
判分口径见 challenges.match_answer：数字整词比对、否定词不算、单向匹配）；
表达/创造是 EFFORT 题，只看是否认真参与，不判对错。

扩库契约：保持本文件结构，往 _RAW 追加即可；正式产品按"每题型×难度≥30 条"扩容，
并走"LLM 生成 + 人工审核"管线。
"""

from __future__ import annotations

from growth.types import Ability, Challenge, ChallengeKind, KIND_ABILITY, ScoreMode

W, L, E, O, C = (ChallengeKind.WARMUP, ChallengeKind.LOGIC, ChallengeKind.EXPRESSION,
                 ChallengeKind.OBSERVATION, ChallengeKind.CREATION)

_RAW = [
    # ================= 脑力热身（专注 · 30 秒、快、即时判） =================
    dict(kind=W, difficulty=1,
         prompt="数一数：1, 3, 5, 7, ? 下一个数字是几？",
         answer="9", accept=["九"],
         explain="这是奇数，每次加 2：7 + 2 = 9。",
         extend="那再往下一个呢？9 + 2 = 11。"),
    dict(kind=W, difficulty=1,
         prompt="一个星期有几天？",
         answer="7", accept=["七"],
         explain="一个星期有 7 天：周一到周日。",
         extend="那两个星期呢？7 + 7 = 14 天。"),
    dict(kind=W, difficulty=1,
         prompt="接着数：2, 4, 6, 8, 下一个是几？",
         answer="10", accept=["十"],
         explain="这是偶数，每次加 2：8 + 2 = 10。",
         extend="偶数都是 2 的好朋友，能被 2 平均分。"),
    dict(kind=W, difficulty=1,
         prompt="一年有几个季节？",
         answer="4", accept=["四", "春夏秋冬"],
         explain="一年有 4 个季节：春、夏、秋、冬。",
         extend="你现在过的是哪个季节呢？"),
    dict(kind=W, difficulty=1,
         prompt="从 10 开始倒数：10、9、…数到的第三个数是几？",
         answer="8", accept=["八"],
         explain="10 是第一个，9 是第二个，8 就是第三个。",
         extend="倒着数就是每次减 1，练熟了减法就快啦。"),
    dict(kind=W, difficulty=1,
         prompt="两只手一共有几根手指？",
         answer="10", accept=["十"],
         explain="一只手 5 根，两只手 5 + 5 = 10 根。",
         extend="那两个人四只手呢？10 + 10 = 20 根。"),
    dict(kind=W, difficulty=2,
         prompt="倒着数：5, 4, 3, … 接下来两个数字是？",
         answer="2,1", accept=["21", "2、1", "2 1", "2和1"],
         explain="倒着数就是每次减 1：3 → 2 → 1。",
         extend="再倒一个就是 0，再往下就要用到负数啦。"),
    dict(kind=W, difficulty=2,
         prompt="红、黄、红、黄、红，按规律下一个是什么颜色？",
         answer="黄", accept=["黄色"],
         explain="红黄交替出现，红的后面轮到黄。",
         extend="如果再加一个，黄的后面又轮到红。"),
    dict(kind=W, difficulty=2,
         prompt="快速心算：6 + 7 等于几？",
         answer="13", accept=["十三"],
         explain="6 + 7：先凑十，6 + 4 = 10，再加 3，等于 13。",
         extend="凑十法是心算的小魔法，加法都能用。"),
    dict(kind=W, difficulty=2,
         prompt="快速心算：15 - 6 等于几？",
         answer="9", accept=["九"],
         explain="15 - 5 = 10，再减 1，等于 9。",
         extend="减法也能拆开算，先减到整十更轻松。"),
    dict(kind=W, difficulty=2,
         prompt="圆形、三角形、圆形、三角形、圆形，下一个是什么形状？",
         answer="三角形", accept=["三角"],
         explain="圆形和三角形轮流出现，圆形后面轮到三角形。",
         extend="生活里也有规律，比如斑马线黑白黑白。"),
    dict(kind=W, difficulty=3,
         prompt="快速心算：3 + 4 + 5 等于几？",
         answer="12", accept=["十二"],
         explain="3 + 4 = 7，7 + 5 = 12。",
         extend="换个顺序也一样：5 + 5 = 10，再 + 2 = 12，加法可以挑好算的先算。"),
    dict(kind=W, difficulty=3,
         prompt="快速心算：8 + 9 等于几？",
         answer="17", accept=["十七"],
         explain="8 + 9：把 9 借 2 给 8 凑成 10，10 + 7 = 17。",
         extend="也可以想 9 + 9 = 18，再减 1。一道题可以有好几条路。"),
    dict(kind=W, difficulty=3,
         prompt="快速心算：30 - 12 等于几？",
         answer="18", accept=["十八"],
         explain="30 - 10 = 20，再减 2，等于 18。",
         extend="把 12 拆成 10 和 2，大数减法就变简单了。"),
    dict(kind=W, difficulty=3,
         prompt="找规律：1, 2, 4, 7, 11, 下一个数字是几？",
         answer="16", accept=["十六"],
         explain="每次加的数在变大：+1、+2、+3、+4，所以下一个是 11 + 5 = 16。",
         extend="规律不一定是加同一个数，也可能是'加的数'本身有规律。"),

    # ================= 逻辑挑战 =================
    dict(kind=L, difficulty=1,
         prompt="小明比小红高，小红比小刚高。谁最矮？",
         answer="小刚", accept=["刚"],
         explain="小明 > 小红 > 小刚，最矮的是小刚。",
         extend="那最高的是谁呢？是小明。"),
    dict(kind=L, difficulty=1,
         prompt="妈妈买了 5 个苹果，吃了 2 个，又买了 3 个，现在有几个？",
         answer="6", accept=["六"],
         explain="5 - 2 = 3，3 + 3 = 6。",
         extend="按发生的顺序一步步算，就不会乱。"),
    dict(kind=L, difficulty=1,
         prompt="哥哥 8 岁，妹妹比哥哥小 2 岁，妹妹几岁？",
         answer="6", accept=["六"],
         explain="比 8 小 2，就是 8 - 2 = 6 岁。",
         extend="'比谁大/小几'，就是加法或减法在说话。"),
    dict(kind=L, difficulty=1,
         prompt="一支铅笔 2 元，买 3 支要多少元？",
         answer="6", accept=["六"],
         explain="2 + 2 + 2 = 6 元，也就是 2 × 3。",
         extend="同样的数加好几次，就是乘法的开始。"),
    dict(kind=L, difficulty=1,
         prompt="排队时，小华前面有 3 个人，后面有 2 个人。队伍里一共有几个人？",
         answer="6", accept=["六"],
         explain="前面 3 人 + 小华自己 1 人 + 后面 2 人 = 6 人。",
         extend="最容易漏掉的就是'自己'——数数时别把自己忘了。"),
    dict(kind=L, difficulty=1,
         prompt="今天是星期一，那么明天是星期几？",
         answer="星期二", accept=["周二", "礼拜二", "二"],
         explain="星期一的下一天就是星期二。",
         extend="那后天呢？再往后数一天，是星期三。"),
    dict(kind=L, difficulty=2,
         prompt="三只兔子住三间房：白兔不住左边，灰兔不住中间，黑兔住右边。谁住中间？",
         answer="白兔", accept=["白"],
         explain="黑兔在右边；灰兔不在中间，只能在左边；剩下中间就是白兔。",
         extend="这种题可以先把'确定的'填上（黑兔右边），再排除，最后剩下的就是答案。"),
    dict(kind=L, difficulty=2,
         prompt="如果今天是星期三，那么后天是星期几？",
         answer="星期五", accept=["周五", "礼拜五", "五"],
         explain="后天是往后数两天：三 → 四 → 五。",
         extend="那大后天呢？再加一天，是星期六。"),
    dict(kind=L, difficulty=2,
         prompt="小明 8 岁，妈妈的年龄是他的 4 倍。妈妈多少岁？",
         answer="32", accept=["三十二"],
         explain="8 的 4 倍：8 + 8 + 8 + 8 = 32 岁。",
         extend="'几倍'就是把同一个数加几次，也就是乘法。"),
    dict(kind=L, difficulty=2,
         prompt="一个数加上 5 等于 12，这个数是几？",
         answer="7", accept=["七"],
         explain="倒过来想：12 - 5 = 7。",
         extend="加法和减法是一对'互相撤销'的好朋友。"),
    dict(kind=L, difficulty=2,
         prompt="甲、乙、丙赛跑：甲不是第一名，丙是最后一名。谁是第一名？",
         answer="乙", accept=["b"],
         explain="丙最后，甲又不是第一，第一名只能是乙。",
         extend="排除法：把不可能的划掉，剩下的就是答案。"),
    dict(kind=L, difficulty=2,
         prompt="停车场有 12 辆车，开走了一半。还剩几辆？",
         answer="6", accept=["六"],
         explain="12 的一半是 6：12 = 6 + 6。",
         extend="'一半'就是平均分成两份，取其中一份。"),
    dict(kind=L, difficulty=3,
         prompt="找规律：2, 4, 8, 16, 下一个数字是几？",
         answer="32", accept=["三十二"],
         explain="每个数都是前一个的 2 倍：16 × 2 = 32。",
         extend="这叫'翻倍'。再下一个就是 32 × 2 = 64，长得很快吧。"),
    dict(kind=L, difficulty=3,
         prompt="院子里有 3 只鸡和 2 只兔。它们一共有多少条腿？",
         answer="14", accept=["十四"],
         explain="鸡 2 条腿：3 × 2 = 6；兔 4 条腿：2 × 4 = 8；6 + 8 = 14 条。",
         extend="分类再相加——把复杂问题拆成两小步，就简单了。"),
    dict(kind=L, difficulty=3,
         prompt="找规律：1, 1, 2, 3, 5, 8, 下一个数字是几？",
         answer="13", accept=["十三"],
         explain="每个数都是前两个数的和：5 + 8 = 13。",
         extend="这是有名的斐波那契数列，向日葵的种子就按它排队。"),
    dict(kind=L, difficulty=3,
         prompt="哥哥给了弟弟 2 颗糖后，两人的糖一样多。原来哥哥比弟弟多几颗？",
         answer="4", accept=["四"],
         explain="哥哥少了 2 颗、弟弟多了 2 颗才拉平，所以原来相差 2 + 2 = 4 颗。",
         extend="给出去的糖'一边减一边加'，差距一下缩小两份。"),

    # ================= 表达挑战（EFFORT：只看认真参与） =================
    dict(kind=E, difficulty=1,
         prompt="请用 30 秒，说一说今天最开心的一件事。",
         explain="说清楚三件小事就很棒：在哪里、发生了什么、你当时什么感觉。",
         extend="下次可以再加一句'为什么开心'，别人就更能感同身受。"),
    dict(kind=E, difficulty=1,
         prompt="介绍你最喜欢的一个玩具：它长什么样？怎么玩？",
         explain="先说样子（颜色/大小），再说玩法，最后说你为什么喜欢它。",
         extend="加一个和它有关的小故事，介绍就活起来了。"),
    dict(kind=E, difficulty=1,
         prompt="你早上从起床到出门，都做了哪些事？按顺序说一说。",
         explain="用'先…然后…接着…最后…'把事情串起来，就是清楚的顺序。",
         extend="顺序说清楚了，写日记也会变简单。"),
    dict(kind=E, difficulty=1,
         prompt="用三句话介绍你自己：名字、最喜欢做的事、最喜欢的食物。",
         explain="一句一个信息，三句就把自己讲明白了。",
         extend="再加一句'我的小目标'，就是一段很棒的自我介绍。"),
    dict(kind=E, difficulty=2,
         prompt="你最好的朋友是什么样的人？用三句话介绍他/她。",
         explain="介绍一个人，可以说：长什么样、喜欢做什么、你们一起做过什么。",
         extend="举一个具体的小例子，比形容词更打动人。"),
    dict(kind=E, difficulty=2,
         prompt="向朋友推荐一本书或一部动画片，说说为什么值得看。",
         explain="推荐要有理由：它讲了什么、哪里最精彩、你看完的感受。",
         extend="试着不剧透结局，让朋友更想自己去看。"),
    dict(kind=E, difficulty=2,
         prompt="描述你的教室：一进门先看到什么？左边和右边各有什么？",
         explain="按方位说（前后左右），听的人脑子里就能画出地图。",
         extend="这叫'空间顺序'，描述房间、操场都能用。"),
    dict(kind=E, difficulty=2,
         prompt="昨天晚饭吃了什么？挑一道最好吃的菜，说说它好吃在哪里。",
         explain="用感官说话：颜色、香味、味道、口感，一样一句。",
         extend="'香得像刚出炉的面包'——用比喻，味道就能被听见。"),
    dict(kind=E, difficulty=3,
         prompt="要把'下雨天'讲给一个从没见过雨的人听，你会怎么说？",
         explain="可以从看到的、听到的、闻到的、摸到的去描述，让他像亲身经历一样。",
         extend="用比喻会更好懂，比如'雨点打在伞上像有人在敲小鼓'。"),
    dict(kind=E, difficulty=3,
         prompt="说服爸爸妈妈周末带你去公园，说出三个理由。",
         explain="好的说服 = 理由 + 对方的好处：'去公园你们也能散步放松'。",
         extend="把最有力的理由放在最后说，印象最深。"),
    dict(kind=E, difficulty=3,
         prompt="把'春天'描述给一个一直住在冬天里的人听。",
         explain="抓住变化：冰化了、芽绿了、燕子回来了、风变软了。",
         extend="对比着说（冬天…而春天…），画面感会翻倍。"),
    dict(kind=E, difficulty=3,
         prompt="讲一讲你学会一件新本领的过程：一开始怎样、中间遇到什么、最后怎样。",
         explain="'开始—困难—解决—结果'，这就是一个完整的小故事。",
         extend="说说当时的心情变化，故事就有了温度。"),

    # ================= 观察挑战 =================
    dict(kind=O, difficulty=1,
         prompt="听这个小故事，找出不合理的地方：'早上，太阳从西边升起，小明吃完早饭去上学。'",
         answer="西边", accept=["西", "太阳", "东边", "东"],
         explain="太阳是从'东边'升起、'西边'落下的，故事里说反了。",
         extend="观察就是和你已经知道的常识比一比，对不上的地方就是线索。"),
    dict(kind=O, difficulty=1,
         prompt="哪里说反了：'小鱼在天上游来游去，小鸟在河里飞来飞去。'",
         answer="说反了", accept=["鱼", "鸟", "天上", "河里", "反"],
         explain="小鱼应该在水里游，小鸟应该在天上飞，两个正好说反了。",
         extend="找'谁在哪里做什么'，是不是各就各位。"),
    dict(kind=O, difficulty=1,
         prompt="哪里不对：'冬天到了，小明穿着短袖短裤去堆雪人。'",
         answer="短袖", accept=["短裤", "穿太少", "冷", "该穿棉袄"],
         explain="冬天很冷，堆雪人要穿厚衣服，穿短袖会冻坏的。",
         extend="季节和穿着要配套——这是生活常识里的规律。"),
    dict(kind=O, difficulty=1,
         prompt="图里画着：夜晚的天空挂着太阳和满天星星。哪里不合理？",
         answer="太阳", accept=["晚上", "夜晚", "月亮"],
         explain="夜晚天上是月亮和星星，太阳只在白天出现。",
         extend="白天和黑夜各有各的'值班员'。"),
    dict(kind=O, difficulty=1,
         prompt="弟弟说：'我用耳朵看了一本好书。'哪里不对？",
         answer="耳朵", accept=["眼睛"],
         explain="看书用的是眼睛；耳朵是用来听的。",
         extend="五官各有分工：眼看、耳听、鼻闻、舌尝、手摸。"),
    dict(kind=O, difficulty=2,
         prompt="哪里不合理：'夏天最热的中午，小红穿着厚厚的棉袄去游泳。'",
         answer="棉袄", accept=["厚", "夏天", "热"],
         explain="夏天很热，穿厚棉袄不合理，何况是去游泳。",
         extend="一句话里可能不止一个线索，多读两遍能找到更多。"),
    dict(kind=O, difficulty=2,
         prompt="一张图里，一只猫在天上自由地飞。这合理吗？为什么？",
         answer="不合理", accept=["不能飞", "不会飞", "没有翅膀", "猫不会飞"],
         explain="猫没有翅膀，不会飞，所以不合理。",
         extend="如果给猫画上翅膀，那就是'想象'啦——分清'现实'和'想象'也是观察力。"),
    dict(kind=O, difficulty=2,
         prompt="不合理在哪：'小红把种子种进沙发里，天天浇水，等它发芽。'",
         answer="沙发", accept=["土", "泥土", "土里"],
         explain="种子要种进泥土里才能发芽，沙发里长不出植物。",
         extend="植物发芽需要土壤、水分和阳光，三样都不能少。"),
    dict(kind=O, difficulty=2,
         prompt="哪里不可能：'爷爷说，他昨天骑着一只大公鸡去上班。'",
         answer="公鸡", accept=["骑鸡", "鸡"],
         explain="公鸡那么小，驮不动人，人不可能骑着公鸡上班。",
         extend="想一想大小和力气配不配，就能发现夸张的地方。"),
    dict(kind=O, difficulty=2,
         prompt="哪里不对：'妹妹用剪刀喝汤，喝得可香了。'",
         answer="剪刀", accept=["勺子", "勺"],
         explain="喝汤要用勺子；剪刀是用来剪东西的，还很危险。",
         extend="工具各有用途，用错了不仅不方便，还可能受伤。"),
    dict(kind=O, difficulty=2,
         prompt="不合理在哪：'花开的声音真好听，小明搬着凳子听了一下午。'",
         answer="声音", accept=["听", "没有声音", "花开没有声"],
         explain="花开是没有声音的，用耳朵听不到，要用眼睛看。",
         extend="有些变化很安静很慢，需要耐心地'看'而不是'听'。"),
    dict(kind=O, difficulty=3,
         prompt="找不合理：'小华把冰块放进冰箱冷冻室，过了一会儿，冰块变成了一杯热水。'",
         answer="热水", accept=["冷冻", "融化", "变热"],
         explain="冷冻室很冷，冰块只会更硬，不可能变成热水。",
         extend="温度是关键线索：冷的地方东西会变冷，不会变热。"),
    dict(kind=O, difficulty=3,
         prompt="哪里不合理：'中午 12 点，小华抬头看见满天的星星眨眼睛。'",
         answer="星星", accept=["中午", "白天"],
         explain="中午阳光太亮，星星的光被盖住了，要到晚上才看得见。",
         extend="星星其实一直都在，只是白天'藏'在了阳光里。"),
    dict(kind=O, difficulty=3,
         prompt="说反了什么：'大轮船在马路上开得飞快，小汽车在河里游得欢。'",
         answer="说反了", accept=["船", "汽车", "马路", "河"],
         explain="轮船走水路，汽车走马路，两个交通工具的位置说反了。",
         extend="交通工具和它的'路'是配对的：飞机—天空，火车—铁轨。"),
    dict(kind=O, difficulty=3,
         prompt="弟弟说：'一斤棉花和一斤铁，当然是铁更重！'他说得对吗？",
         answer="不对", accept=["一样重", "一样"],
         explain="都是'一斤'，重量就一样重；铁只是看起来更小更结实。",
         extend="大小和重量不是一回事——小小的铁块和大大的棉花可以一样重。"),

    # ================= 创造挑战（EFFORT：只看认真参与） =================
    dict(kind=C, difficulty=1,
         prompt="如果你有一只会飞的恐龙，你最想带它去哪里？为什么？",
         explain="没有标准答案——你的理由越特别越好玩。",
         extend="再想想：到了那里，你和恐龙会一起做什么？"),
    dict(kind=C, difficulty=1,
         prompt="如果你的铅笔会说话，它会对你说什么？",
         explain="想想铅笔每天的'生活'：被削、写字、掉地上……它会有什么心情？",
         extend="替物品说话，就是把自己'变成'它——这叫拟人。"),
    dict(kind=C, difficulty=1,
         prompt="给你的宠物（或想养的宠物）设计一个超能力，它能用来做什么？",
         explain="超能力 + 用处，说清这两样就是完整的设计。",
         extend="再想一个'副作用'，故事就更有意思了。"),
    dict(kind=C, difficulty=1,
         prompt="如果家里的门是彩虹做的，会发生什么有趣的事？",
         explain="大胆想：颜色会变吗？摸起来什么感觉？穿过去会怎样？",
         extend="把一个平常的东西换种材料，就能变出一个新世界。"),
    dict(kind=C, difficulty=2,
         prompt="发明一种新文具，它能帮你做一件现在做不到的事。它叫什么、能做什么？",
         explain="先想'我有什么烦恼'，再想'什么东西能解决它'，发明就出来了。",
         extend="给它取个名字，画面感会更强，比如'橡皮飞船'。"),
    dict(kind=C, difficulty=2,
         prompt="设计一个新节日：它叫什么名字？那一天大家都做什么？",
         explain="节日 = 名字 + 日子 + 大家一起做的事，三样齐了就成立。",
         extend="再设计一样节日专属食物，就更像真的了。"),
    dict(kind=C, difficulty=2,
         prompt="如果你能变成一种动物过一天，你想变成什么？那一天你会做什么？",
         explain="选一种动物，用它的本领去做你平时做不到的事。",
         extend="想想不方便的地方：变成鱼就不能吃冰淇淋啦。"),
    dict(kind=C, difficulty=2,
         prompt="你要在太空开一家小店，卖什么给外星人？为什么他们会喜欢？",
         explain="想想外星人可能缺什么、好奇什么，你的货就好卖了。",
         extend="给你的小店起个响亮的名字吧。"),
    dict(kind=C, difficulty=3,
         prompt="给天上的云朵起一个新名字，并说说为什么这么叫。",
         explain="可以从云的样子、颜色、让你想到什么去起名，理由最重要。",
         extend="同一朵云，不同的人会起不同的名字——这就是想象力的魅力。"),
    dict(kind=C, difficulty=3,
         prompt="发明一台机器人，它可以帮小朋友做'除了写作业以外'的任何三件事。是哪三件？",
         explain="三件事最好各不相同：一件帮忙、一件保护、一件陪玩。",
         extend="为什么不让它代写作业呢？想想'帮忙'和'代替'的区别。"),
    dict(kind=C, difficulty=3,
         prompt="如果海水变成甜的，世界会发生什么变化？说出三个。",
         explain="顺着链条想：海里的鱼会怎样？喝水的人会怎样？做盐的人呢？",
         extend="一个变化会带出一串变化——这叫连锁反应。"),
    dict(kind=C, difficulty=3,
         prompt="把'时间'想象成一个人：他长什么样？每天都在做什么？",
         explain="把看不见的东西画出样子来，是很高级的想象。",
         extend="他会喜欢谁、讨厌谁？珍惜时间的人和浪费时间的人，他怎么对待？"),
]


def load_bank() -> list[Challenge]:
    """把原始字典编译成 Challenge 列表，自动补全 ability / score_mode / cid。"""
    out: list[Challenge] = []
    counters: dict[str, int] = {}
    for raw in _RAW:
        kind: ChallengeKind = raw["kind"]
        n = counters.get(kind.value, 0) + 1
        counters[kind.value] = n
        mode = ScoreMode.OBJECTIVE if raw.get("answer") else ScoreMode.EFFORT
        out.append(Challenge(
            cid=f"{kind.value}-{n:02d}",
            kind=kind,
            ability=KIND_ABILITY[kind],
            difficulty=raw["difficulty"],
            prompt=raw["prompt"],
            score_mode=mode,
            answer=raw.get("answer"),
            accept=list(raw.get("accept", [])),
            options=list(raw.get("options", [])),
            explain=raw.get("explain", ""),
            extend=raw.get("extend", ""),
        ))
    return out
